[functions.send-push]
enabled = true
verify_jwt = false
import_map = "./functions/send-push/deno.json"
entrypoint = "./functions/send-push/index.ts"

[functions.generar-historial]
enabled = true
verify_jwt = true
import_map = "./functions/generar-historial/deno.json"
entrypoint = "./functions/generar-historial/index.ts"

[functions.send-email-auth]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-email-auth/index.ts"
